// Generated by gencpp from file coni_mpc/LocalBarrier.msg
// DO NOT EDIT!


#ifndef CONI_MPC_MESSAGE_LOCALBARRIER_H
#define CONI_MPC_MESSAGE_LOCALBARRIER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace coni_mpc
{
template <class ContainerAllocator>
struct LocalBarrier_
{
  typedef LocalBarrier_<ContainerAllocator> Type;

  LocalBarrier_()
    : header()
    , query_center_N()
    , A_row_major()
    , b()
    , c(0.0)
    , rmse(0.0)
    , max_abs_error(0.0)
    , condition_number(0.0)
    , rank(0)
    , min_singular_value(0.0)
    , max_singular_value(0.0)
    , query_count(0)
    , valid(false)  {
      A_row_major.assign(0.0);
  }
  LocalBarrier_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , query_center_N(_alloc)
    , A_row_major()
    , b(_alloc)
    , c(0.0)
    , rmse(0.0)
    , max_abs_error(0.0)
    , condition_number(0.0)
    , rank(0)
    , min_singular_value(0.0)
    , max_singular_value(0.0)
    , query_count(0)
    , valid(false)  {
  (void)_alloc;
      A_row_major.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _query_center_N_type;
  _query_center_N_type query_center_N;

   typedef boost::array<double, 9>  _A_row_major_type;
  _A_row_major_type A_row_major;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _b_type;
  _b_type b;

   typedef double _c_type;
  _c_type c;

   typedef double _rmse_type;
  _rmse_type rmse;

   typedef double _max_abs_error_type;
  _max_abs_error_type max_abs_error;

   typedef double _condition_number_type;
  _condition_number_type condition_number;

   typedef int32_t _rank_type;
  _rank_type rank;

   typedef double _min_singular_value_type;
  _min_singular_value_type min_singular_value;

   typedef double _max_singular_value_type;
  _max_singular_value_type max_singular_value;

   typedef uint32_t _query_count_type;
  _query_count_type query_count;

   typedef uint8_t _valid_type;
  _valid_type valid;





  typedef boost::shared_ptr< ::coni_mpc::LocalBarrier_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coni_mpc::LocalBarrier_<ContainerAllocator> const> ConstPtr;

}; // struct LocalBarrier_

typedef ::coni_mpc::LocalBarrier_<std::allocator<void> > LocalBarrier;

typedef boost::shared_ptr< ::coni_mpc::LocalBarrier > LocalBarrierPtr;
typedef boost::shared_ptr< ::coni_mpc::LocalBarrier const> LocalBarrierConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coni_mpc::LocalBarrier_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coni_mpc::LocalBarrier_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::coni_mpc::LocalBarrier_<ContainerAllocator1> & lhs, const ::coni_mpc::LocalBarrier_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.query_center_N == rhs.query_center_N &&
    lhs.A_row_major == rhs.A_row_major &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c &&
    lhs.rmse == rhs.rmse &&
    lhs.max_abs_error == rhs.max_abs_error &&
    lhs.condition_number == rhs.condition_number &&
    lhs.rank == rhs.rank &&
    lhs.min_singular_value == rhs.min_singular_value &&
    lhs.max_singular_value == rhs.max_singular_value &&
    lhs.query_count == rhs.query_count &&
    lhs.valid == rhs.valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::coni_mpc::LocalBarrier_<ContainerAllocator1> & lhs, const ::coni_mpc::LocalBarrier_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace coni_mpc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::coni_mpc::LocalBarrier_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coni_mpc::LocalBarrier_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coni_mpc::LocalBarrier_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coni_mpc::LocalBarrier_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coni_mpc::LocalBarrier_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coni_mpc::LocalBarrier_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coni_mpc::LocalBarrier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "582aa024af4e145e9928e13dd367c1d7";
  }

  static const char* value(const ::coni_mpc::LocalBarrier_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x582aa024af4e145eULL;
  static const uint64_t static_value2 = 0x9928e13dd367c1d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::coni_mpc::LocalBarrier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coni_mpc/LocalBarrier";
  }

  static const char* value(const ::coni_mpc::LocalBarrier_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coni_mpc::LocalBarrier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Point query_center_N\n"
"float64[9] A_row_major\n"
"geometry_msgs/Vector3 b\n"
"float64 c\n"
"float64 rmse\n"
"float64 max_abs_error\n"
"float64 condition_number\n"
"int32 rank\n"
"float64 min_singular_value\n"
"float64 max_singular_value\n"
"uint32 query_count\n"
"bool valid\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::coni_mpc::LocalBarrier_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coni_mpc::LocalBarrier_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.query_center_N);
      stream.next(m.A_row_major);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.rmse);
      stream.next(m.max_abs_error);
      stream.next(m.condition_number);
      stream.next(m.rank);
      stream.next(m.min_singular_value);
      stream.next(m.max_singular_value);
      stream.next(m.query_count);
      stream.next(m.valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalBarrier_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coni_mpc::LocalBarrier_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coni_mpc::LocalBarrier_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "query_center_N: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.query_center_N);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "A_row_major: ";
    if (v.A_row_major.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.A_row_major.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.A_row_major[i]);
    }
    if (v.A_row_major.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "b: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.b);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "c: ";
    Printer<double>::stream(s, indent + "  ", v.c);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rmse: ";
    Printer<double>::stream(s, indent + "  ", v.rmse);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_abs_error: ";
    Printer<double>::stream(s, indent + "  ", v.max_abs_error);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "condition_number: ";
    Printer<double>::stream(s, indent + "  ", v.condition_number);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rank: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rank);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "min_singular_value: ";
    Printer<double>::stream(s, indent + "  ", v.min_singular_value);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_singular_value: ";
    Printer<double>::stream(s, indent + "  ", v.max_singular_value);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "query_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.query_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONI_MPC_MESSAGE_LOCALBARRIER_H
