# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from coni_mpc/LocalBarrier.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class LocalBarrier(genpy.Message):
  _md5sum = "582aa024af4e145e9928e13dd367c1d7"
  _type = "coni_mpc/LocalBarrier"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
geometry_msgs/Point query_center_N
float64[9] A_row_major
geometry_msgs/Vector3 b
float64 c
float64 rmse
float64 max_abs_error
float64 condition_number
int32 rank
float64 min_singular_value
float64 max_singular_value
uint32 query_count
bool valid

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','query_center_N','A_row_major','b','c','rmse','max_abs_error','condition_number','rank','min_singular_value','max_singular_value','query_count','valid']
  _slot_types = ['std_msgs/Header','geometry_msgs/Point','float64[9]','geometry_msgs/Vector3','float64','float64','float64','float64','int32','float64','float64','uint32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,query_center_N,A_row_major,b,c,rmse,max_abs_error,condition_number,rank,min_singular_value,max_singular_value,query_count,valid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LocalBarrier, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.query_center_N is None:
        self.query_center_N = geometry_msgs.msg.Point()
      if self.A_row_major is None:
        self.A_row_major = [0.] * 9
      if self.b is None:
        self.b = geometry_msgs.msg.Vector3()
      if self.c is None:
        self.c = 0.
      if self.rmse is None:
        self.rmse = 0.
      if self.max_abs_error is None:
        self.max_abs_error = 0.
      if self.condition_number is None:
        self.condition_number = 0.
      if self.rank is None:
        self.rank = 0
      if self.min_singular_value is None:
        self.min_singular_value = 0.
      if self.max_singular_value is None:
        self.max_singular_value = 0.
      if self.query_count is None:
        self.query_count = 0
      if self.valid is None:
        self.valid = False
    else:
      self.header = std_msgs.msg.Header()
      self.query_center_N = geometry_msgs.msg.Point()
      self.A_row_major = [0.] * 9
      self.b = geometry_msgs.msg.Vector3()
      self.c = 0.
      self.rmse = 0.
      self.max_abs_error = 0.
      self.condition_number = 0.
      self.rank = 0
      self.min_singular_value = 0.
      self.max_singular_value = 0.
      self.query_count = 0
      self.valid = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.query_center_N.x, _x.query_center_N.y, _x.query_center_N.z))
      buff.write(_get_struct_9d().pack(*self.A_row_major))
      _x = self
      buff.write(_get_struct_7di2dIB().pack(_x.b.x, _x.b.y, _x.b.z, _x.c, _x.rmse, _x.max_abs_error, _x.condition_number, _x.rank, _x.min_singular_value, _x.max_singular_value, _x.query_count, _x.valid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.query_center_N is None:
        self.query_center_N = geometry_msgs.msg.Point()
      if self.b is None:
        self.b = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.query_center_N.x, _x.query_center_N.y, _x.query_center_N.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 72
      self.A_row_major = _get_struct_9d().unpack(str[start:end])
      _x = self
      start = end
      end += 81
      (_x.b.x, _x.b.y, _x.b.z, _x.c, _x.rmse, _x.max_abs_error, _x.condition_number, _x.rank, _x.min_singular_value, _x.max_singular_value, _x.query_count, _x.valid,) = _get_struct_7di2dIB().unpack(str[start:end])
      self.valid = bool(self.valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.query_center_N.x, _x.query_center_N.y, _x.query_center_N.z))
      buff.write(self.A_row_major.tostring())
      _x = self
      buff.write(_get_struct_7di2dIB().pack(_x.b.x, _x.b.y, _x.b.z, _x.c, _x.rmse, _x.max_abs_error, _x.condition_number, _x.rank, _x.min_singular_value, _x.max_singular_value, _x.query_count, _x.valid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.query_center_N is None:
        self.query_center_N = geometry_msgs.msg.Point()
      if self.b is None:
        self.b = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.query_center_N.x, _x.query_center_N.y, _x.query_center_N.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 72
      self.A_row_major = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      _x = self
      start = end
      end += 81
      (_x.b.x, _x.b.y, _x.b.z, _x.c, _x.rmse, _x.max_abs_error, _x.condition_number, _x.rank, _x.min_singular_value, _x.max_singular_value, _x.query_count, _x.valid,) = _get_struct_7di2dIB().unpack(str[start:end])
      self.valid = bool(self.valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_7di2dIB = None
def _get_struct_7di2dIB():
    global _struct_7di2dIB
    if _struct_7di2dIB is None:
        _struct_7di2dIB = struct.Struct("<7di2dIB")
    return _struct_7di2dIB
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
