#!/bin/bash
set -e
cd "$(dirname "$0")/.."
source devel/setup.bash

RUN_ROOT="results/slack3_jitter_singlecore_$(date +%Y%m%d-%H%M%S)"
SCRIPT="scripts/run_vw_three_controller_20seed.py"
echo "Run root: $RUN_ROOT"
echo "Running collision cases with --jobs 1"

python3 $SCRIPT --v-values "2.5" --w-values "2.5" --seed-start 3 --seed-end 3 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "2.5" --seed-start 42 --seed-end 42 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "2.5" --seed-start 44 --seed-end 44 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "2.5" --seed-start 48 --seed-end 48 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "2.5" --seed-start 58 --seed-end 58 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "2.5" --seed-start 62 --seed-end 62 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "2.5" --seed-start 65 --seed-end 65 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "2.5" --seed-start 97 --seed-end 97 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "3" --seed-start 3 --seed-end 3 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "3" --seed-start 27 --seed-end 27 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "3" --seed-start 36 --seed-end 36 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "3" --seed-start 37 --seed-end 37 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "3" --seed-start 42 --seed-end 42 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "3" --seed-start 44 --seed-end 44 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "3" --seed-start 47 --seed-end 47 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "3" --seed-start 58 --seed-end 58 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "3" --seed-start 62 --seed-end 62 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "3" --seed-start 65 --seed-end 65 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "3" --seed-start 82 --seed-end 82 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "3" --seed-start 84 --seed-end 84 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "2.5" --w-values "3" --seed-start 97 --seed-end 97 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 3 --seed-end 3 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 8 --seed-end 8 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 9 --seed-end 9 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 12 --seed-end 12 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 16 --seed-end 16 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 17 --seed-end 17 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 22 --seed-end 22 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 23 --seed-end 23 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 28 --seed-end 28 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 33 --seed-end 33 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 36 --seed-end 36 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 37 --seed-end 37 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 38 --seed-end 38 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 43 --seed-end 43 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 44 --seed-end 44 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 46 --seed-end 46 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 48 --seed-end 48 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 52 --seed-end 52 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 53 --seed-end 53 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 56 --seed-end 56 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 57 --seed-end 57 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 58 --seed-end 58 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 61 --seed-end 61 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 63 --seed-end 63 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 66 --seed-end 66 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 67 --seed-end 67 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 68 --seed-end 68 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 74 --seed-end 74 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 76 --seed-end 76 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 80 --seed-end 80 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 81 --seed-end 81 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 82 --seed-end 82 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 85 --seed-end 85 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 87 --seed-end 87 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 88 --seed-end 88 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 89 --seed-end 89 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 92 --seed-end 92 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 94 --seed-end 94 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 96 --seed-end 96 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 97 --seed-end 97 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 98 --seed-end 98 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "2.5" --seed-start 100 --seed-end 100 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 1 --seed-end 1 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 3 --seed-end 3 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 5 --seed-end 5 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 8 --seed-end 8 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 12 --seed-end 12 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 17 --seed-end 17 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 18 --seed-end 18 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 20 --seed-end 20 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 22 --seed-end 22 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 23 --seed-end 23 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 28 --seed-end 28 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 29 --seed-end 29 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 35 --seed-end 35 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 36 --seed-end 36 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 37 --seed-end 37 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 39 --seed-end 39 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 41 --seed-end 41 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 44 --seed-end 44 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 47 --seed-end 47 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 48 --seed-end 48 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 51 --seed-end 51 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 52 --seed-end 52 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 53 --seed-end 53 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 55 --seed-end 55 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 56 --seed-end 56 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 57 --seed-end 57 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 58 --seed-end 58 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 61 --seed-end 61 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 63 --seed-end 63 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 65 --seed-end 65 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 66 --seed-end 66 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 67 --seed-end 67 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 69 --seed-end 69 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 74 --seed-end 74 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 80 --seed-end 80 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 81 --seed-end 81 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 82 --seed-end 82 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 85 --seed-end 85 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 87 --seed-end 87 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 91 --seed-end 91 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 92 --seed-end 92 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 94 --seed-end 94 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 96 --seed-end 96 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 97 --seed-end 97 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"
python3 $SCRIPT --v-values "3" --w-values "3" --seed-start 100 --seed-end 100 --obs 100 --jobs 1 --no-aggregate --run-root "$RUN_ROOT"

# 聚合
python3 scripts/aggregate_vw_three_controller_metrics.py "$RUN_ROOT"
echo "Done: $RUN_ROOT"