// Generated by gencpp from file onboard_detector/TrackedObstacleArray.msg
// DO NOT EDIT!


#ifndef ONBOARD_DETECTOR_MESSAGE_TRACKEDOBSTACLEARRAY_H
#define ONBOARD_DETECTOR_MESSAGE_TRACKEDOBSTACLEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <onboard_detector/TrackedObstacle.h>

namespace onboard_detector
{
template <class ContainerAllocator>
struct TrackedObstacleArray_
{
  typedef TrackedObstacleArray_<ContainerAllocator> Type;

  TrackedObstacleArray_()
    : header()
    , obstacles()  {
    }
  TrackedObstacleArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::onboard_detector::TrackedObstacle_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::onboard_detector::TrackedObstacle_<ContainerAllocator> >> _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedObstacleArray_

typedef ::onboard_detector::TrackedObstacleArray_<std::allocator<void> > TrackedObstacleArray;

typedef boost::shared_ptr< ::onboard_detector::TrackedObstacleArray > TrackedObstacleArrayPtr;
typedef boost::shared_ptr< ::onboard_detector::TrackedObstacleArray const> TrackedObstacleArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::onboard_detector::TrackedObstacleArray_<ContainerAllocator1> & lhs, const ::onboard_detector::TrackedObstacleArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.obstacles == rhs.obstacles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::onboard_detector::TrackedObstacleArray_<ContainerAllocator1> & lhs, const ::onboard_detector::TrackedObstacleArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace onboard_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6a3a6c3418c99b8e13b32d276fbf0c1";
  }

  static const char* value(const ::onboard_detector::TrackedObstacleArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6a3a6c3418c99b8ULL;
  static const uint64_t static_value2 = 0xe13b32d276fbf0c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "onboard_detector/TrackedObstacleArray";
  }

  static const char* value(const ::onboard_detector::TrackedObstacleArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"onboard_detector/TrackedObstacle[] obstacles\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: onboard_detector/TrackedObstacle\n"
"int32 slot_id\n"
"bool is_dynamic\n"
"geometry_msgs/Vector3 position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 size\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::onboard_detector::TrackedObstacleArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedObstacleArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::onboard_detector::TrackedObstacleArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::onboard_detector::TrackedObstacleArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "obstacles: ";
    if (v.obstacles.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::onboard_detector::TrackedObstacle_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.obstacles[i]);
    }
    if (v.obstacles.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ONBOARD_DETECTOR_MESSAGE_TRACKEDOBSTACLEARRAY_H
