// Generated by gencpp from file onboard_detector/TrackedObstacle.msg
// DO NOT EDIT!


#ifndef ONBOARD_DETECTOR_MESSAGE_TRACKEDOBSTACLE_H
#define ONBOARD_DETECTOR_MESSAGE_TRACKEDOBSTACLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace onboard_detector
{
template <class ContainerAllocator>
struct TrackedObstacle_
{
  typedef TrackedObstacle_<ContainerAllocator> Type;

  TrackedObstacle_()
    : slot_id(0)
    , is_dynamic(false)
    , position()
    , velocity()
    , size()  {
    }
  TrackedObstacle_(const ContainerAllocator& _alloc)
    : slot_id(0)
    , is_dynamic(false)
    , position(_alloc)
    , velocity(_alloc)
    , size(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _slot_id_type;
  _slot_id_type slot_id;

   typedef uint8_t _is_dynamic_type;
  _is_dynamic_type is_dynamic;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::onboard_detector::TrackedObstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::onboard_detector::TrackedObstacle_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedObstacle_

typedef ::onboard_detector::TrackedObstacle_<std::allocator<void> > TrackedObstacle;

typedef boost::shared_ptr< ::onboard_detector::TrackedObstacle > TrackedObstaclePtr;
typedef boost::shared_ptr< ::onboard_detector::TrackedObstacle const> TrackedObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::onboard_detector::TrackedObstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::onboard_detector::TrackedObstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::onboard_detector::TrackedObstacle_<ContainerAllocator1> & lhs, const ::onboard_detector::TrackedObstacle_<ContainerAllocator2> & rhs)
{
  return lhs.slot_id == rhs.slot_id &&
    lhs.is_dynamic == rhs.is_dynamic &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.size == rhs.size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::onboard_detector::TrackedObstacle_<ContainerAllocator1> & lhs, const ::onboard_detector::TrackedObstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace onboard_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::onboard_detector::TrackedObstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::onboard_detector::TrackedObstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::onboard_detector::TrackedObstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::onboard_detector::TrackedObstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::onboard_detector::TrackedObstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::onboard_detector::TrackedObstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::onboard_detector::TrackedObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50d60af2ec9911de5b888d1721cba72d";
  }

  static const char* value(const ::onboard_detector::TrackedObstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50d60af2ec9911deULL;
  static const uint64_t static_value2 = 0x5b888d1721cba72dULL;
};

template<class ContainerAllocator>
struct DataType< ::onboard_detector::TrackedObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "onboard_detector/TrackedObstacle";
  }

  static const char* value(const ::onboard_detector::TrackedObstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::onboard_detector::TrackedObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 slot_id\n"
"bool is_dynamic\n"
"geometry_msgs/Vector3 position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 size\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::onboard_detector::TrackedObstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::onboard_detector::TrackedObstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.slot_id);
      stream.next(m.is_dynamic);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedObstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::onboard_detector::TrackedObstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::onboard_detector::TrackedObstacle_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "slot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.slot_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_dynamic: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_dynamic);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "size: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ONBOARD_DETECTOR_MESSAGE_TRACKEDOBSTACLE_H
