// Generated by gencpp from file local_sensing_node/DynamicObstacleState.msg
// DO NOT EDIT!


#ifndef LOCAL_SENSING_NODE_MESSAGE_DYNAMICOBSTACLESTATE_H
#define LOCAL_SENSING_NODE_MESSAGE_DYNAMICOBSTACLESTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace local_sensing_node
{
template <class ContainerAllocator>
struct DynamicObstacleState_
{
  typedef DynamicObstacleState_<ContainerAllocator> Type;

  DynamicObstacleState_()
    : obstacle_id(0)
    , is_dynamic(false)
    , geometry_type()
    , position()
    , velocity()
    , size()  {
    }
  DynamicObstacleState_(const ContainerAllocator& _alloc)
    : obstacle_id(0)
    , is_dynamic(false)
    , geometry_type(_alloc)
    , position(_alloc)
    , velocity(_alloc)
    , size(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _obstacle_id_type;
  _obstacle_id_type obstacle_id;

   typedef uint8_t _is_dynamic_type;
  _is_dynamic_type is_dynamic;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _geometry_type_type;
  _geometry_type_type geometry_type;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> const> ConstPtr;

}; // struct DynamicObstacleState_

typedef ::local_sensing_node::DynamicObstacleState_<std::allocator<void> > DynamicObstacleState;

typedef boost::shared_ptr< ::local_sensing_node::DynamicObstacleState > DynamicObstacleStatePtr;
typedef boost::shared_ptr< ::local_sensing_node::DynamicObstacleState const> DynamicObstacleStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::local_sensing_node::DynamicObstacleState_<ContainerAllocator1> & lhs, const ::local_sensing_node::DynamicObstacleState_<ContainerAllocator2> & rhs)
{
  return lhs.obstacle_id == rhs.obstacle_id &&
    lhs.is_dynamic == rhs.is_dynamic &&
    lhs.geometry_type == rhs.geometry_type &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.size == rhs.size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::local_sensing_node::DynamicObstacleState_<ContainerAllocator1> & lhs, const ::local_sensing_node::DynamicObstacleState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace local_sensing_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1cd6ca51f05588daa1bdc717cdb87ba";
  }

  static const char* value(const ::local_sensing_node::DynamicObstacleState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1cd6ca51f05588dULL;
  static const uint64_t static_value2 = 0xaa1bdc717cdb87baULL;
};

template<class ContainerAllocator>
struct DataType< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "local_sensing_node/DynamicObstacleState";
  }

  static const char* value(const ::local_sensing_node::DynamicObstacleState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 obstacle_id\n"
"bool is_dynamic\n"
"string geometry_type\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 size\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::local_sensing_node::DynamicObstacleState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacle_id);
      stream.next(m.is_dynamic);
      stream.next(m.geometry_type);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DynamicObstacleState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::local_sensing_node::DynamicObstacleState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "obstacle_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.obstacle_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_dynamic: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_dynamic);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "geometry_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.geometry_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "size: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCAL_SENSING_NODE_MESSAGE_DYNAMICOBSTACLESTATE_H
