// Generated by gencpp from file local_sensing_node/DynamicObstacleStateArray.msg
// DO NOT EDIT!


#ifndef LOCAL_SENSING_NODE_MESSAGE_DYNAMICOBSTACLESTATEARRAY_H
#define LOCAL_SENSING_NODE_MESSAGE_DYNAMICOBSTACLESTATEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <local_sensing_node/DynamicObstacleState.h>

namespace local_sensing_node
{
template <class ContainerAllocator>
struct DynamicObstacleStateArray_
{
  typedef DynamicObstacleStateArray_<ContainerAllocator> Type;

  DynamicObstacleStateArray_()
    : header()
    , obstacles()  {
    }
  DynamicObstacleStateArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> >> _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> const> ConstPtr;

}; // struct DynamicObstacleStateArray_

typedef ::local_sensing_node::DynamicObstacleStateArray_<std::allocator<void> > DynamicObstacleStateArray;

typedef boost::shared_ptr< ::local_sensing_node::DynamicObstacleStateArray > DynamicObstacleStateArrayPtr;
typedef boost::shared_ptr< ::local_sensing_node::DynamicObstacleStateArray const> DynamicObstacleStateArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator1> & lhs, const ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.obstacles == rhs.obstacles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator1> & lhs, const ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace local_sensing_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2411b68bc8e07baa293691aaa8841ee6";
  }

  static const char* value(const ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2411b68bc8e07baaULL;
  static const uint64_t static_value2 = 0x293691aaa8841ee6ULL;
};

template<class ContainerAllocator>
struct DataType< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "local_sensing_node/DynamicObstacleStateArray";
  }

  static const char* value(const ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"local_sensing_node/DynamicObstacleState[] obstacles\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: local_sensing_node/DynamicObstacleState\n"
"int32 obstacle_id\n"
"bool is_dynamic\n"
"string geometry_type\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 size\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DynamicObstacleStateArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::local_sensing_node::DynamicObstacleStateArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "obstacles: ";
    if (v.obstacles.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::local_sensing_node::DynamicObstacleState_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.obstacles[i]);
    }
    if (v.obstacles.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCAL_SENSING_NODE_MESSAGE_DYNAMICOBSTACLESTATEARRAY_H
