// Generated by gencpp from file quadrotor_msgs/MincoTrajectory.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_MINCOTRAJECTORY_H
#define QUADROTOR_MSGS_MESSAGE_MINCOTRAJECTORY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct MincoTrajectory_
{
  typedef MincoTrajectory_<ContainerAllocator> Type;

  MincoTrajectory_()
    : header()
    , trajectory_id(0)
    , action(0)
    , num_order(0)
    , num_segment(0)
    , start_yaw(0.0)
    , final_yaw(0.0)
    , init_state()
    , final_state()
    , waypoints_x()
    , waypoints_y()
    , waypoints_z()
    , time()
    , mag_coeff(0.0)
    , order()
    , start_time()
    , local_start_t(0.0)
    , occ_state(0)
    , debug_info()  {
      init_state.assign(0.0);

      final_state.assign(0.0);
  }
  MincoTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , trajectory_id(0)
    , action(0)
    , num_order(0)
    , num_segment(0)
    , start_yaw(0.0)
    , final_yaw(0.0)
    , init_state()
    , final_state()
    , waypoints_x(_alloc)
    , waypoints_y(_alloc)
    , waypoints_z(_alloc)
    , time(_alloc)
    , mag_coeff(0.0)
    , order(_alloc)
    , start_time()
    , local_start_t(0.0)
    , occ_state(0)
    , debug_info(_alloc)  {
  (void)_alloc;
      init_state.assign(0.0);

      final_state.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _trajectory_id_type;
  _trajectory_id_type trajectory_id;

   typedef uint32_t _action_type;
  _action_type action;

   typedef uint32_t _num_order_type;
  _num_order_type num_order;

   typedef uint32_t _num_segment_type;
  _num_segment_type num_segment;

   typedef double _start_yaw_type;
  _start_yaw_type start_yaw;

   typedef double _final_yaw_type;
  _final_yaw_type final_yaw;

   typedef boost::array<double, 12>  _init_state_type;
  _init_state_type init_state;

   typedef boost::array<double, 12>  _final_state_type;
  _final_state_type final_state;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _waypoints_x_type;
  _waypoints_x_type waypoints_x;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _waypoints_y_type;
  _waypoints_y_type waypoints_y;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _waypoints_z_type;
  _waypoints_z_type waypoints_z;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _time_type;
  _time_type time;

   typedef double _mag_coeff_type;
  _mag_coeff_type mag_coeff;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _order_type;
  _order_type order;

   typedef ros::Time _start_time_type;
  _start_time_type start_time;

   typedef double _local_start_t_type;
  _local_start_t_type local_start_t;

   typedef uint32_t _occ_state_type;
  _occ_state_type occ_state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _debug_info_type;
  _debug_info_type debug_info;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ACTION_ADD)
  #undef ACTION_ADD
#endif
#if defined(_WIN32) && defined(ACTION_ABORT)
  #undef ACTION_ABORT
#endif
#if defined(_WIN32) && defined(ACTION_WARN_START)
  #undef ACTION_WARN_START
#endif
#if defined(_WIN32) && defined(ACTION_WARN_FINAL)
  #undef ACTION_WARN_FINAL
#endif
#if defined(_WIN32) && defined(ACTION_WARN_IMPOSSIBLE)
  #undef ACTION_WARN_IMPOSSIBLE
#endif

  enum {
    ACTION_ADD = 1u,
    ACTION_ABORT = 2u,
    ACTION_WARN_START = 3u,
    ACTION_WARN_FINAL = 4u,
    ACTION_WARN_IMPOSSIBLE = 5u,
  };


  typedef boost::shared_ptr< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct MincoTrajectory_

typedef ::quadrotor_msgs::MincoTrajectory_<std::allocator<void> > MincoTrajectory;

typedef boost::shared_ptr< ::quadrotor_msgs::MincoTrajectory > MincoTrajectoryPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::MincoTrajectory const> MincoTrajectoryConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.trajectory_id == rhs.trajectory_id &&
    lhs.action == rhs.action &&
    lhs.num_order == rhs.num_order &&
    lhs.num_segment == rhs.num_segment &&
    lhs.start_yaw == rhs.start_yaw &&
    lhs.final_yaw == rhs.final_yaw &&
    lhs.init_state == rhs.init_state &&
    lhs.final_state == rhs.final_state &&
    lhs.waypoints_x == rhs.waypoints_x &&
    lhs.waypoints_y == rhs.waypoints_y &&
    lhs.waypoints_z == rhs.waypoints_z &&
    lhs.time == rhs.time &&
    lhs.mag_coeff == rhs.mag_coeff &&
    lhs.order == rhs.order &&
    lhs.start_time == rhs.start_time &&
    lhs.local_start_t == rhs.local_start_t &&
    lhs.occ_state == rhs.occ_state &&
    lhs.debug_info == rhs.debug_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00d62cdfef43fbf8db0e1a3a7f618be6";
  }

  static const char* value(const ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00d62cdfef43fbf8ULL;
  static const uint64_t static_value2 = 0xdb0e1a3a7f618be6ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/MincoTrajectory";
  }

  static const char* value(const ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# the trajectory id, starts from \"1\".\n"
"uint32 trajectory_id\n"
"\n"
"# the action command for trajectory server.\n"
"uint32 ACTION_ADD                  =   1\n"
"uint32 ACTION_ABORT                =   2\n"
"uint32 ACTION_WARN_START           =   3\n"
"uint32 ACTION_WARN_FINAL           =   4\n"
"uint32 ACTION_WARN_IMPOSSIBLE      =   5\n"
"uint32 action\n"
"\n"
"# the order of trajectory.\n"
"uint32 num_order\n"
"uint32 num_segment\n"
"\n"
"# the polynomial coecfficients of the trajectory.\n"
"float64 start_yaw\n"
"float64 final_yaw\n"
"float64[12] init_state\n"
"float64[12] final_state\n"
"float64[] waypoints_x\n"
"float64[] waypoints_y\n"
"float64[] waypoints_z\n"
"float64[] time\n"
"float64   mag_coeff\n"
"uint32[]  order\n"
"time start_time\n"
"float64 local_start_t\n"
"#the occ state of trajectory.\n"
"uint32 occ_state\n"
"string debug_info\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.trajectory_id);
      stream.next(m.action);
      stream.next(m.num_order);
      stream.next(m.num_segment);
      stream.next(m.start_yaw);
      stream.next(m.final_yaw);
      stream.next(m.init_state);
      stream.next(m.final_state);
      stream.next(m.waypoints_x);
      stream.next(m.waypoints_y);
      stream.next(m.waypoints_z);
      stream.next(m.time);
      stream.next(m.mag_coeff);
      stream.next(m.order);
      stream.next(m.start_time);
      stream.next(m.local_start_t);
      stream.next(m.occ_state);
      stream.next(m.debug_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MincoTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::MincoTrajectory_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trajectory_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.trajectory_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.action);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num_order: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num_order);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num_segment: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num_segment);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "start_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.start_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "final_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.final_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "init_state: ";
    if (v.init_state.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.init_state.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.init_state[i]);
    }
    if (v.init_state.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "final_state: ";
    if (v.final_state.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.final_state.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.final_state[i]);
    }
    if (v.final_state.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "waypoints_x: ";
    if (v.waypoints_x.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.waypoints_x.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.waypoints_x[i]);
    }
    if (v.waypoints_x.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "waypoints_y: ";
    if (v.waypoints_y.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.waypoints_y.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.waypoints_y[i]);
    }
    if (v.waypoints_y.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "waypoints_z: ";
    if (v.waypoints_z.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.waypoints_z.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.waypoints_z[i]);
    }
    if (v.waypoints_z.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "time: ";
    if (v.time.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.time.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.time[i]);
    }
    if (v.time.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mag_coeff: ";
    Printer<double>::stream(s, indent + "  ", v.mag_coeff);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "order: ";
    if (v.order.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.order.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.order[i]);
    }
    if (v.order.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "start_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.start_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "local_start_t: ";
    Printer<double>::stream(s, indent + "  ", v.local_start_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "occ_state: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.occ_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "debug_info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.debug_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_MINCOTRAJECTORY_H
