(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TRAJECTORY_ID-VAL
          TRAJECTORY_ID
          ACTION-VAL
          ACTION
          NUM_ORDER-VAL
          NUM_ORDER
          NUM_SEGMENT-VAL
          NUM_SEGMENT
          START_YAW-VAL
          START_YAW
          FINAL_YAW-VAL
          FINAL_YAW
          INIT_STATE-VAL
          INIT_STATE
          FINAL_STATE-VAL
          FINAL_STATE
          WAYPOINTS_X-VAL
          WAYPOINTS_X
          WAYPOINTS_Y-VAL
          WAYPOINTS_Y
          WAYPOINTS_Z-VAL
          WAYPOINTS_Z
          TIME-VAL
          TIME
          MAG_COEFF-VAL
          MAG_COEFF
          ORDER-VAL
          ORDER
          START_TIME-VAL
          START_TIME
          LOCAL_START_T-VAL
          LOCAL_START_T
          OCC_STATE-VAL
          OCC_STATE
          DEBUG_INFO-VAL
          DEBUG_INFO
))