(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          ACCELERATION-VAL
          ACCELERATION
          JERK-VAL
          JERK
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
          ATTITUDE-VAL
          ATTITUDE
          THRUST-VAL
          THRUST
          YAW-VAL
          YAW
          YAW_DOT-VAL
          YAW_DOT
          VEL_NORM-VAL
          VEL_NORM
          ACC_NORM-VAL
          ACC_NORM
          KX-VAL
          KX
          KV-VAL
          KV
          TRAJECTORY_ID-VAL
          TRAJECTORY_ID
          TRAJECTORY_FLAG-VAL
          TRAJECTORY_FLAG
))