(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          Q0-VAL
          Q0
          Q1-VAL
          Q1
          Q2-VAL
          Q2
          Q3-VAL
          Q3
          GYRO_X-VAL
          GYRO_X
          GYRO_Y-VAL
          GYRO_Y
          GYRO_Z-VAL
          GYRO_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          DOWN_DIST-VAL
          DOWN_DIST
          TOP_DIST-VAL
          TOP_DIST
          LATI-VAL
          LATI
          LONGTI-VAL
          LONGTI
          PRESS-VAL
          PRESS
          VG_X-VAL
          VG_X
          VG_Y-VAL
          VG_Y
          VG_Z-VAL
          VG_Z
          AILERON-VAL
          AILERON
          ELEVATOR-VAL
          ELEVATOR
          THROTTLE-VAL
          THROTTLE
          RUDDER-VAL
          RUDDER
          FC_TIMESTAMP_MS-VAL
          FC_TIMESTAMP_MS
          VO_FLAG-VAL
          VO_FLAG
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          ANTI_LONGTI-VAL
          ANTI_LONGTI
          ANTI_PRESS-VAL
          ANTI_PRESS
))